### ISSUE TITLE
POGOProtos\Data\PlayerData did not read the full length

### ISSUE THREAD

**Issue by NicklasWallgren** [AeonLucid/POGOProtos#100]
Uncaught Exception: \POGOProtos\Data\PlayerData did not read the full length.

Length left is "5"

**Comment by rubenvereecken** [comment]
Where did you get that exception from though.

**Comment by NicklasWallgren** [comment]
While unmarshalling the GetPlayerResponse. This indicates that the current definition is not entirely correct.

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
