### ISSUE TITLE
Disconnect the Session?

### ISSUE THREAD

**Issue by drakbar** [AeonLucid/POGOProtos#107]
Is the something like a session.Shutdown()? I know there isn't that exact one but a similar functionally (besides killing the loop). I did not see anything in RequestMessages either for something like this. I have the startup code from the demo shoved into a function that gets called from the HandleCommands loop, and would like to add a disconnect command so a user could log out without closing the window and change the passed arguments to the StartUp. BTW great work on the API, once I get more familiar with it and setup some basic stuff I am hoping to wrap it all up inside an Xna project.

**Comment by Grover-c13** [comment]
Are you on the right repo? this is just proto stuff

**Comment by drakbar** [comment]
I am on the master, so most likely no...

**Comment by Grover-c13** [comment]
Yeah but this isnt an API, its just the proto files the api use :P are you looking for POGOLib? https://github.com/AeonLucid/POGOLib

**Comment by drakbar** [comment]
Well I am using those and most likely this question belongs over there...forgive me I am a little noobish when it comes to gitHub

**Comment by drakbar** [comment]
Should I move this party over there?

**Comment by Grover-c13** [comment]
yeah your probably more likely to get help

**Comment by rubenvereecken** [comment]
:wave:
