### ISSUE TITLE
CaptureAward has some invalid types

### ISSUE THREAD

**Issue by tjhorner** [AeonLucid/POGOProtos#109]
Well, _all_ invalid types. They're all sent as `bytes`.

![image](https://cloud.githubusercontent.com/assets/2646487/17273479/780f43f0-566a-11e6-9ad7-fdd00c647bf8.png)

This doesn't look correct at all... I'll MITM my phone today while capturing a Pokemon and see if I can get a rough message from that.

**Comment by tjhorner** [comment]
Notes:
- `candy (3)` seems to always be <03, 00, 00>

Will update when I have more data...

**Comment by Grover-c13** [comment]
if you pass it into the right type it will work.

**Comment by tjhorner** [comment]
> if you pass it into the right type it will work.

This is not the goal of this project though. We want to have a correct message here so that people can use it and have the right values.

**Comment by Lennix** [comment]
You means this?

Response for CatchPokemon  { status: 'CATCH_SUCCESS',
  captured_pokemon_id: 'REDACTED',
  capture_award: 
   { activity_type: [ 'ACTIVITY_CATCH_POKEMON' ],
     xp: Int32Array { '0': 100 },
     candy: Int32Array { '0': 3 },
     stardust: Int32Array { '0': 100 } } }

**Comment by tjhorner** [comment]
Yes. That doesn't seem to work for me with `repeated int32`. Is it working for you with this exact proto file?

**Comment by Lennix** [comment]
Yes, thats with the currect POGOProtos. 

For multiple activities (like great throw):

Response for CatchPokemon  { status: 'CATCH_SUCCESS',
  capture_award: 
   { activity_type: [ 'ACTIVITY_CATCH_POKEMON', 'ACTIVITY_CATCH_GREAT_THROW' ],
     xp: Int32Array { '0': 100, '1': 50 },
     candy: Int32Array { '0': 3, '1': 0 },
     stardust: Int32Array { '0': 100, '1': 0 } } }

**Comment by tjhorner** [comment]
Odd. What language are you using with this?

**Comment by Lennix** [comment]
POGOLib C# and pokemon-go-mitm-node (javascript)

**Comment by Grover-c13** [comment]
It works for java api too in its current state

**Comment by mikuso** [comment]
Please see my pull request. I suspect this will fix your problem.
