### ISSUE TITLE
Is POGOProtos.Inventory.InventoryItem deleted_item_key incorrect?

### ISSUE THREAD

**Issue by laverdet** [AeonLucid/POGOProtos#111]
It seems like InventoryItem has an incorrect type. I'm currently running with the following changes applied and everything is great.. But this message is in a very commonly used request (GetInventoryResponse) so I'm hesitant to submit a PR because I feel like others would have run into this already.

Also when this key is set it means a Pokemon has been deleted from the player's "inventory" (i.e. it was released), and `key` represents the pokemon_id. There may be other cases, but if so I haven't seen them yet.

Has anyone else seen this yet?

```
--- a/src/POGOProtos/Inventory/InventoryItem.proto
+++ b/src/POGOProtos/Inventory/InventoryItem.proto
@@ -5,6 +5,9 @@ import "POGOProtos/Inventory/InventoryItemData.proto";

 message InventoryItem {
        int64 modified_timestamp_ms = 1;
-       int64 deleted_item_key = 2;
+       message DeletedItem {
+               fixed64 key = 1;
+       }
+       DeletedItem deleted_item_key = 2;
        .POGOProtos.Inventory.InventoryItemData inventory_item_data = 3;
 }
```

**Comment by valyard** [comment]
Seems to be true. I've been getting parsing errors when releasing pokemons until applied your fix.

**Comment by rubenvereecken** [comment]
O my god that would explain so much. I have _never_ seen this field set, had to work around for keeping up with Pokemon inventory state. I'd just get messages with the pokemon in it, still not that field.

Please consider a PR!
