### ISSUE TITLE
StartGymBattle response is empty

### ISSUE THREAD

**Issue by Bloontede** [AeonLucid/POGOProtos#114]
e.g.
GymId = "the long gym ID I got with GetGymDetails"
DefendingPokemonId = the Id of the pokemon of the first member of the gym from GetGymDetails
AttackingPokemonIds = [list of 6 Ids of the player's pokemon - resp. 1 if the gym is owned by the player's team]

Response:
Status = 3
Success = Unset

Anyone else tried it and could confirm?

**Comment by vmarchaud** [comment]
status code signify a bad request, we dont know why it isnt always working.
btw the first request for StartGymBattle you should get a UNSET because the servers are redirecting you to another endpoint.

**Comment by krzys-h** [comment]
See #97

**Comment by Bloontede** [comment]
Confirmed working with the fixed64 fix. Thanks :)

**Comment by jamie2016-1** [comment]
@Bloontede Im still having issues with this care to give me some pointers or help. Im still getting an empty response. Would be much appreciated.
