### ISSUE TITLE
RPC API Changes

### ISSUE THREAD

**Issue by loicortola** [AeonLucid/POGOProtos#116]
Hi @Grover-c13, @AeonLucid 
thanks for the awesome work.
I am having an issue and cannot retrieve the catchable pokemons (I am using the Java API from @Grover-c13 ). The error suggests an IndexOutOfBoundsException which makes me think something could have been changed on the API.
Any chance you guys have experienced some issues as well?
(Or maybe am I doing it wrong!)
How can I help? (Anything to get me started on protobuf and how to fix this ^^)

Thanks a lot

**Comment by valyard** [comment]
Can you provide more info what method(s) you are using?
Are you referring to `GET_MAP_OBJECTS = 106` method to get nearby pokemon in a `s2-geometry` cells list?

**Comment by Grover-c13** [comment]
Can you please reopen this issue on the JavaAPI repo

**Comment by loicortola** [comment]
@valyard absolutely. Just double checked and it is indeed where the magic... doesn't happen ^^

@Grover-c13 Sure, will do.

**Comment by rubenvereecken** [comment]
Closing this one then
