### ISSUE TITLE
RFQ: Additional Information Fields

### ISSUE THREAD

**Issue by eslindsey** [AeonLucid/POGOProtos#125]
I'm trying to figure out where the appropriate place to put information which is tightly coupled to the game, and not related to a higher-level implementation, should go. For example, the PokemonType associated with a PokemonMove, and other information like Damage and the information required to calculate DPS. This is rapidly shifting information (for example it was changed by Niantic in their most recent update yesterday or the day before as part of balancing changes). It's also information that I cannot always find in the wild--for example what type of attack is `ABSORB = 113`; I can't find any information about it online. I don't think this information belongs in the final high level implementation ("bots" or whatever), but it might not be appropriate here. If not here, then perhaps the API is the correct home for this?

**Comment by trisk** [comment]
This seems like the correct place to document the semantics of fields and enum values. A tool like estan/protoc-gen-doc can produce beautiful documentation from structured comments.

**Comment by rubenvereecken** [comment]
I definitely like this information to be inside the proto schemas, we can always revise them every time we get a changelog from Niantic. The protobuf schemas really are the place where all semantics should be described though this purpose of them has mostly been neglected so far.

**Comment by eslindsey** [comment]
Well, the reason for the comment request is because it isn't actually a proto or part of the communication. We would ideally take the information obtained from reverse engineering the game and store it somewhere usable (not as documentation). For example, a JSON file in POGOProtos could be easily maintained and deserialized into:

```
class PokemonMoveInfo
{
    public readonly PokemonMove Move;
    public readonly PokemonMovementType MoveType;
    public readonly PokemonType AttackType;
    public readonly int Damage;
    public readonly int Duration;
}
```

and so so. Obviously as I mentioned before, this is not part of the communications protocols. But it's as close to the game as the protocols are, so this project seems to be a good candidate for a location to store the information, for use by higher level projects. Making them classes makes them easily extensible, as well. With two of these entries, it would be easy to make a `PokemonData.CalculateEffectiveDps(PokemonMoveInfo moveInfo)` that would take into account the STA bonus and all other related information.

**Comment by rubenvereecken** [comment]
@eslindsey I agree on having modules of reusable Pokemon logic. I made a node module for exactly this purpose: https://github.com/PokemonGo-Enhanced/node-pokemongo-data

It should be in language specific repositories though, preferably with shared JSON underneath like that repository I linked has JSON files in its root directory. I will consider any and all PRs regarding this.

**Comment by eslindsey** [comment]
@rubenvereecken Where did you obtain the data from? I've been ripping apart the IPA and APK files, figuring I'd find it in there, but I'm having trouble tracking it down. My research indicates it might be in the protocols somewhere?

**Comment by trisk** [comment]
https://github.com/IronB3ard/PokemonGoDumper/tree/0.33-dump/LastestDumps has a current IL class dump, which includes various structures for moves, including one which is actually a protobuf:

```
class MoveSettingsProto
{
        // Fields
        static int UniqueIdFieldNumber = 1;
        static int AnimationIdFieldNumber = 2;
        static int TypeFieldNumber = 3;
        static int PowerFieldNumber = 4;
        static int AccuracyChanceFieldNumber = 5;
        static int CriticalChanceFieldNumber = 6;
        static int HealScalarFieldNumber = 7;
        static int StaminaLossScalarFieldNumber = 8;
        static int TrainerLevelMinFieldNumber = 9;
        static int TrainerLevelMaxFieldNumber = 10;
        static int VfxNameFieldNumber = 11;
        static int DurationMsFieldNumber = 12;
        static int DamageWindowStartMsFieldNumber = 13;
        static int DamageWindowEndMsFieldNumber = 14;
        static int EnergyDeltaFieldNumber = 15;
        Generic _parser;
        HoloPokemonMove uniqueId_;
        int animationId_;
        HoloPokemonType type_;
        float power_;
        float accuracyChance_;
        float criticalChance_;
        float healScalar_;
        float staminaLossScalar_;
        int trainerLevelMin_;
        int trainerLevelMax_;
        String vfxName_;
        int durationMs_;
        int damageWindowStartMs_;
        int damageWindowEndMs_;
        int energyDelta_;
...
```

I think we should include all of the internal protobuf schemas in this repo even if they're not always seen over the wire.

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
