### ISSUE TITLE
uint64 for golang

### ISSUE THREAD

**Issue by freman** [AeonLucid/POGOProtos#128]
So, we've encountered a wonderful issue where Go json.Marshal of uint64 gives us number javascript JSON.parse() can't handle

``` javascript
JSON.parse('{"BigInt": 15793061490787194429}')
```

Gives Object {BigInt: 15793061490787195000}

We worked around it by adding `,string` before `,omitempty` on all the uint64's

``` go
type thing struct {
    EncounterId     uint64  `protobuf:"fixed64,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,string,omitempty"`
}
```

Basically this sed

``` bash
sed -i "" 's/\(uint64.*\)\(,omitempty\)/\1,string\2/' $file
```

This gives us

``` js
JSON.parse('{"BigInt": "15793061490787194429"}')
```

**Comment by Grover-c13** [comment]
Please see http://www.2ality.com/2012/07/large-integers.html
JavaScript uses floating points for all numbers, so you have precision issues with large numbers.
not really an issue for POGOProtos

**Comment by swynter-ladbrokes** [comment]
I know, and it's more of a go-protobufs problem, but I figured with your compile script/go-helper making it add ,string to the json tags would be easy. We've worked around it ourselves but might be helpful for others.

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
