### ISSUE TITLE
random status_code 3 on several protos

### ISSUE THREAD

**Issue by dnsBlah** [AeonLucid/POGOProtos#129]
I'm receiving randomly status_code 3 on my requests with a empty returns field.
Anyone knows what it means and why it occures?

I have this with useItemCapture, catchPokemon, getMapObjects

It happens random, not related to throttling as I loop through it 10 times,
for getMapObjects
each time the sleep is 5 + loopcount, and increase the radius to scan
for catch and itemcapture i just loop it a few times, and then return Null

After 10 times failing, re-login from scratch, and still the same error.

**Comment by Grover-c13** [comment]
bad request

**Comment by Grover-c13** [comment]
To add, you are missing required fields in the message  or incorrect data

**Comment by dnsBlah** [comment]
But thats really funny that it does work just 100 pokestops ago, and then it doesnt
same with raspberries and catching :S

Data to send:

```
cells: [5171986839241752576L, 5171986841389236224L, 5171986843536719872L, 5171986845684203520L, 5171986847831687168L, 5171986849979170816L, 5171986852126654464L, 5171986854274138112L, 5171986856421621760L, 5171986858569105408L, 5171986860716589056L, 5171986862864072704L, 5171986865011556352L, 5171986867159040000L, 5171986869306523648L, 5171986871454007296L, 5171986873601490944L, 5171986875748974592L, 5171986877896458240L, 5171986880043941888L, 5171986882191425536L, 5171986884338909184L, 5171986886486392832L]
locatoins lat: 51.647697 lng: 5.04844
timestamps: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

Payload 

```
payload = [Request_pb2.Request(
            request_type=RequestType_pb2.GET_MAP_OBJECTS,
            request_message=GetMapObjectsMessage_pb2.GetMapObjectsMessage(
                cell_id=cells,
                since_timestamp_ms=timestamps,
                latitude=latitude,
                longitude=longitude
            ).SerializeToString()
        )]
```

Just right now it already ran for a while again ...

**Comment by csnewman** [comment]
I think issues like this could be solved with #36 as the status code has meaning then, not just a number.

**Comment by dnsBlah** [comment]
If I follow this:

> Field: ValueType UNDEFINED
> Field: ValueType SUCCESS
> Field: ValueType BAD_RESPONSE
> Field: ValueType ACTION_ERROR
> Field: ValueType DISPATCH_ERROR
> Field: ValueType SERVER_ERROR
> Field: ValueType ASSIGNMENT_ERROR
> Field: ValueType PROTOCOL_ERROR
> Field: ValueType AUTHENTICATION_ERROR
> Field: ValueType CANCELLED_REQUEST
> Field: ValueType UNKNOWN_ERROR
> Field: ValueType NO_RETRIES_ERROR
> Field: ValueType UNAUTHORIZED_ERROR
> Field: ValueType PARSING_ERROR

My status code should be, ACTION_ERROR
Yet I don't understand why or how this can happen.

```
payload = [Request_pb2.Request(
            request_type=RequestType_pb2.USE_ITEM_CAPTURE,
            request_message=UseItemCaptureMessage_pb2.UseItemCaptureMessage(
                item_id=item_id,
                encounter_id=pokemon.encounter_id,
                spawn_point_guid=pokemon.spawn_point_id
            ).SerializeToString()
        )]
```

The error pops up totally random

**Comment by Grover-c13** [comment]
Are you sure youre not getting spam soft-banned and you need to sleep 10 seconds between map calls now: https://www.reddit.com/r/pokemongodev/comments/4vwtia/ip_address_limitation_added/

**Comment by krzys-h** [comment]
Also, your code is wrong (assuming you are using the latest protos), the field is called spawn_point_id not spawn_point_guid
https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Networking/Requests/Messages/UseItemCaptureMessage.proto#L9

**Comment by dnsBlah** [comment]
@Grover-c13 Hi, 
currently not receiving it with get_map_objects at the moment, but the use_item_capture is. And I made dynamic delays when it fails. Untill max. 10 times then it will just re-login

@krzys-h Thanks for your comment, I just changed it, but the issue still remains. I actually recently did compile the proto's a few days ago
Same issue happens on catchPokemon once a while.

**Comment by rubenvereecken** [comment]
Once you guys figure this out, mind sending a PR to document status code 3? As far as I know, it's undocumented atm.

**Comment by vmarchaud** [comment]
There is PR #36 which aim to document the all status_code but we are not sure about the actual value of each enum.

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
