### ISSUE TITLE
Is the scan time doubled again ?? 

### ISSUE THREAD

**Issue by thisismohitgupta** [AeonLucid/POGOProtos#167]
http://www.geekpoint0.com/console/2016/8/4/dqsj955r4mo56yd5ceuj7eisw2hovf

**Comment by beeb** [comment]
I would suggest you go have a read over at https://www.reddit.com/r/pokemongodev/

**Comment by GameoverNiantic** [comment]
unknown6 is solved. cannot believe the people here still deleting the link and wasting time and resources to re-invent the wheel 
src @ https://www.sendspace.com/file/5h1q29

**Comment by beeb** [comment]
password protected zip

**Comment by GameoverNiantic** [comment]
password will be released tonight
