### ISSUE TITLE
Update unkown6

### ISSUE THREAD

**Issue by drakbar** [AeonLucid/POGOProtos#170]
So I am not 100% certain on how to update the Protos to reflect the recently developed fix, thus I am opening an issue and not a Pull request. However, I am interested to know how this would be accomplished.

My guess is to update POGOProtos.Networking.Envelopes.Unkown6 to something similar to [Signature.proto](https://github.com/Eliminster0/pgoapi/blob/master/pgoapi/protos/Signature.proto). Though I know there must be something more to it. I am looking for help in fully implementing the update :grinning:

**Comment by AeonLucid** [comment]
I'm working on this at the moment.

**Comment by rubenvereecken** [comment]
Referencing #169

**Comment by drakbar** [comment]
My bad guys! I am really interested to know for personal knowledge how it is accomplished. I will be paying close attention!
