### ISSUE TITLE
Lure module missing

### ISSUE THREAD

**Issue by maierfelix** [AeonLucid/POGOProtos#182]
Enum key _ITEM_LURE_MODULE_ missing in:
[POGOProtos/Inventory/Item/ItemId.proto](https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Inventory/Item/ItemId.proto)

**Comment by Lennix** [comment]
So they changed TROY_DISC? or where does it come from?

Nope - still have TROY_DISC in my inventory.

**Comment by maierfelix** [comment]
Checked this and _Lure Modules_ get called _Troy Disc_. A bit confusing
