### ISSUE TITLE
battleresult.proto next_defender_pokemon_id

### ISSUE THREAD

**Issue by ramarro123** [AeonLucid/POGOProtos#185]
it's correct that int64 it's used for next_defender_pokemon_id?
since the id should be used for StartGymBattle i think that it should be fixed64 or i am missing something?

**Comment by jamie2016-1** [comment]
No it should be fixed64. When I check the Proto file for StartGymBattle its fixed64, this has to be consistent between calls:

https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Networking/Requests/Messages/StartGymBattleMessage.proto

**Comment by jamie2016-1** [comment]
@ramarro123 have you successfully started a gym battle and got the response back ok from that?

**Comment by jamie2016-1** [comment]
@ramarro123 if you have skype let me know we can go through it.

**Comment by ramarro123** [comment]
i successfully start a battle, the problem it's the round#2 after the won.
No, i am not available on skype, sorry.

And, on StartGymBattle it's correct (fixed64) so the link that you give me, point to the fact that ti's correct.

the problem it's that on battleresult.proto it's it64 and not fixed64, StartGymBattle it's correct (And it don't match battleresult.proto)

**Comment by jamie2016-1** [comment]
Email available? Ill send you a mail now and we can go through it. Are you call this via C Sharp?

**Comment by jamie2016-1** [comment]
@ramarro123 im having issues with gymbattlestart dont suppose we can help each other?

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
