### ISSUE TITLE
Unknown request & response

### ISSUE THREAD

**Issue by maierfelix** [AeonLucid/POGOProtos#187]
Request: http://pastebin.com/k0tn338G
Response: http://pastebin.com/bQ6eY0wh
The traffic gets send, when opening the players pokemon party and click on a pokemon, to show its stats. Current proto files seem to fail on decoding it.

**Comment by Lennix** [comment]
Could you try protoc decode raw on the binary request/response and post it here?

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
