### ISSUE TITLE
[Request] Drive warning when above 30kph

### ISSUE THREAD

**Issue by ghost** [AeonLucid/POGOProtos#189]
In the latest pogo version, when a player goes above 30 kph 
a warning about playing while driving pops up,
and it doesn't allow the player to do anything until he clicks a button labled
"I'm a passenger", 

Is it possible to tell when the warning pops up yet?
if it isn't implemented yet could you look into it?

Thank you,
Chemi.

**Comment by trisk** [comment]
The warning is not part of the API. It's just internal to the app.

**Comment by ghost** [comment]
@trisk mhm okay thanks
