### ISSUE TITLE
StartGmyBattle returns empty response - C Sharp API Version 

### ISSUE THREAD

**Issue by jamie2016-1** [AeonLucid/POGOProtos#192]
I am passing in the GymId from the GetGymDetails, the Defending Pokemon is the First Member pokemon from the GetGymDetails, and I pass in 6 pokemon to attack if team != my team is different or 1 if the teams are the same.

The responseEnvelope looks like this : 

`{ "statusCode": 2, "requestId": "1469378659230941192", "requests": [ { "requestType": "START_GYM_BATTLE", "requestMessage": "CiMxYzk0YmNhNDg5YjQ0ZjhmOWM2ZTUxNmJjYjk2Njk5Zi4xNhIw8MwHK6sFGaXMrXyKjJrb7qY9lbmQQbV+YV5SNdKKfktnuWLbbiWi5t4x8bd6WLcXGUbJgSmTIBkRIUBOa9UDY0RAKQI542RvfVLA" } ], "unknown6": [ { "requestType": 6, "unknown2": { "unknown1": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmRRGHy1cJGqqgFTvRVKm3YgTFepFvccd9sGk/rZJwsrJ7wWObvfD4y8BVo4KrnvlmmANKz33MSs4n9MeC4j1QeK1+Q5BNNqNjPBIccqEo5F6S7qxNgguhtdenhPw3tG/2YnCjWZKHMUFff1QHZ3s+WJfn4u8xMssXfKpAMbd41Fo8+38YFkW8K1ZewxFLGAK9gf4OzW3i/35H0EZmfdS3DsvXJgCpc9EXo628skXDScsqxyWL7hEdqbvFQiKzsgbdg26poDIKAFRliE+ZthMxsqekFKyvxQyZOeyGIOLj+7nK7QBLuPh26OxvGf6pnfkVWUXNmxLFuzxBkisZ/56fo95OPGYriNkhqgmyhDzCMRnGSk9XyxN/3/XM0FQ9nOdiNBvOIT9LIVgXkkayooqbPWQBS5xTZDBrczpCUitOG1f0JcslvgwED8Y6siFkEOXWn+sx9Fu8J16NVcPFEGJqmPQpPwJnpAsnSdZIfZZB82Dhl2gROukkLXlr/dDMqsS1cLUP7qGi9nMCc8w0OmIMB4JDho6ucOrAsbwhbKz8wfdahZ/UtJ1qtMouQbBlo08KVFANdayGZMe7lxmhJk6e3sYcLVneKlNeMAdtiK9SRrapSunUBKlimVMfw/l9StqAco3YWuRVFqIZoE1y0VrdMCEeBj0PxeflBjUX7gy7Q==" } } ], "latitude": 40.773554494281143, "longitude": -73.959923955819278, "altitude": 1.7977072587188445, "authTicket": { "start": "eecHrXZ9TemBaTiOO+fPtboW2ByfUWnm5d7x9x9JYlZCpqpOc7Sm0/1OwrxGtrJU7Ve4XukYE3A5L/bM08ZqFAd21dhSn/hBdAHKVBCqtRw=", "expireTimestampMs": "1471041054743", "end": "beBt9JbY5ta0VOn1ogCIZw==" }, "unknown12": "989" }` 

Can someone else try and run this with the C Sharp API. I have tried everything, the logic actually delays calling the StartGymBattle and loops for N number of times retrying and pausing between each. To give the server a chance etc.

It would be great to know if someone has actually got this to work using the C Sharp API. 

Thanks again for any info/input.

**Comment by jamie2016-1** [comment]
An update here. I setup python to try and call the same service via the Python API and it worked perfectly! So this does appear to be a C# API issue. If someone else could also try that would be great.

**Comment by Na4uto** [comment]
had an issue with the c api , works perfectly on python so as jamie said there is an issue in c api

**Comment by jamie2016-1** [comment]
Actually I got it to work on the C# API. Forgot about this tread. It can be closed.
