### ISSUE TITLE
Error: Illegal group end indicator for Message .POGOProtos.Networking.Envelopes.ResponseEnvelope: 7 (not a group)

### ISSUE THREAD

**Issue by didix16** [AeonLucid/POGOProtos#193]
Hi, has title says, I receive this error:
Error: Illegal group end indicator for Message .POGOProtos.Networking.Envelopes.ResponseEnvelope: 7 (not a group)

when trying to get the playerResponse (after the first initil request).

Any ideas about ?

I'm viewing an other repository that is using this:
message ResponseEnvelop {
  optional int32 unknown1 = 1;
  optional int64 unknown2 = 2;
  optional string api_url = 3;
  optional Unknown6 unknown6 = 6;
  optional AuthTicket auth_ticket = 7;
  repeated bytes payload = 100;

  message Unknown6 {
    required int32 unknown1 = 1;
    required Unknown2 unknown2 = 2;

```
message Unknown2 {
  optional uint64 unknown1 = 1;
  repeated bytes storeitems = 2;
  repeated bytes currencies = 3;
  optional string unknown4 = 4;
}
```

  }

  message AuthTicket {
        optional bytes start = 1;
        optional uint64 expire_timestamp_ms = 2;
        optional bytes end = 3;
    }

and its working.. It's so weird

**Comment by laverdet** [comment]
I believe this is an issue in protobuf.js (which it looks like you're using). See dcodeIO/protobuf.js#432 for details.

I have a fork on npm with the fix: `npm install protobufjs-laverdet-proto3-packed-fix` and then just use that instead of require('protobufjs').

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
