### ISSUE TITLE
Problem with filter by moves in NecroBot

### ISSUE THREAD

**Issue by wuaito4** [AeonLucid/POGOProtos#197]
Hi I'm from Argentina (sorry for my English). I want filter pokemon by moves in Config.json but I can't. The bot gives an error message. I tried a lot of combinations but I give up.

The "error message":
## JSON Exception: Error converting value "Blizzard" to type ´System.Collections.Generic.List`1[POGOProtos.Enums.PokemonMove]´. Path ´PokemonsTransferFilter.Ditto.Moves[0]´, line 1793, position 26.

If u can tell me how configure to filter pokemons by moves I would be very grateful. Sorry for my basic English and poor programming knowledge. Thank you!

**Comment by Grover-c13** [comment]
I think this is the wrong project, try NebroBots github

**Comment by dnsBlah** [comment]
xD

**Comment by wuaito4** [comment]
Sorry guys!
