### ISSUE TITLE
Unknown25 is changed

### ISSUE THREAD

**Issue by iGio90** [AeonLucid/POGOProtos#205]
it is now ->   unknown25: '7363665268261373700' (still static)

**Comment by Kermel** [comment]
Maybe a lame question but could you please indicate how to find this out ?
(which tools are best for catching and then decoding the official app requests) ?

I think that besides unknown25 it is also good to know the hash used in DownloadSettings request message (?)

**Comment by trisk** [comment]
@kermel  https://github.com/rastapasta/pokemon-go-mitm for fields which exist in the current protobuf spec (it's not good at identifying new fields)

**Comment by Kermel** [comment]
Thanks, I will try to run it (seems not just a piece of cake :-) )

**Comment by iGio90** [comment]
@trisk @rastapasta we found unk25. It's the encrypted sha1 hash of the version code

**Comment by iGio90** [comment]
https://github.com/AeonLucid/POGOProtos/pull/208

**Comment by AeonLucid** [comment]
Closing this issue, it's fixed.
