### ISSUE TITLE
RequestType 600

### ISSUE THREAD

**Issue by pvanassen** [AeonLucid/POGOProtos#210]
With the latest update, the client sends out a request type 600, with no parameters. It seems to always responds with " ".

**Comment by Grover-c13** [comment]
This is challenge request for capcha, protos have bee patched for it already

**Comment by pvanassen** [comment]
Indeed added with https://github.com/AeonLucid/POGOProtos/commit/e9b4e769becf525374732d9ce4cd25e682f73cd3#diff-b55444abaa1cdeaad0c661cd0f23f880
