### ISSUE TITLE
Use clang-format

### ISSUE THREAD

**Issue by iphydf** [AeonLucid/POGOProtos#211]
Use clang-format (with Language: Proto) to auto-format the proto files. This PR (at the time of writing) has incorrect formatting (mixing tabs and spaces). It would be good to run clang-format as part of the Travis CI build to ensure that it's upheld. (Personally I'd go for https://developers.google.com/protocol-buffers/docs/style but I'll leave that up to @AeonLucid).

(Copy-pasted the above from #202).

**Comment by AeonLucid** [comment]
Added, sorry for taking so long and ignoring your PR @iphydf
