### ISSUE TITLE
How to compile this into CSharp in windows 10? 

### ISSUE THREAD

**Issue by IDarkCobalt** [AeonLucid/POGOProtos#213]
I already installed the latest version of python.

When I tried to compile the project:

![image](https://cloud.githubusercontent.com/assets/21072175/17955183/dfbf7f4a-6ab2-11e6-852c-2ca600497d42.png)

**Comment by trisk** [comment]
You need the `protoc` command in your `%PATH%` or specified with `--protoc-path`.

**Comment by Kermel** [comment]
...or you must put the fullpath to the "protoc.exe" file as part of the python command (using -p attribute)
for example: "-p c:\software\protoc\bin\protoc.exe"

So full command then will be something like this:
"python compile_pretty.py -p c:\somedir\protoc\protoc.exe csharp"

**Comment by AeonLucid** [comment]
Closing this issue.
