### ISSUE TITLE
0.3.7 Update

### ISSUE THREAD

**Issue by firebolt55439** [AeonLucid/POGOProtos#233]
Just opening a discussion for any protobuf-related changes due to the new 0.3.7 (1.7.0 iOS) update. It appears unknown6 structure has changed (again), as well as some initial requests made on authentication.

**Comment by apavlinovic** [comment]
Can anyone verify if the egg distance tracking is recorded more frequently in 0.37.0?

**Comment by Kermel** [comment]
Has anyone also found out what is the current value for unknown25 ?

**Comment by itchywasabi** [comment]
UK25 #208

**Comment by Grover-c13** [comment]
the encryption for the Signature/SignalLog/U6 has changed, so no.

**Comment by gise88** [comment]
is there someone who is already working on it?

**Comment by langit7** [comment]
Just got force update to 0.39. botting is dead now

**Comment by vankxr** [comment]
Signature changed?

I am running my own API and Bot with this protos in nodejs and its working normally.

EDIT: Stopped working atm...

**Comment by vankxr** [comment]
I've got this from a 0.39.1 initial authentication:

```
1: 1
2: 2
3: 1
4 {
  1: 3
}
```

The current protos don't have any fourth field at the response envelope, so... I don't know where to go next :|

**Comment by Grover-c13** [comment]
Thats just the safteynet auth envelope sent on android, normal requwst envelopes resume after this one

Sent from my Samsung GALAXY S5

-------- Original message --------

**Comment by vankxr** [comment]
@Grover-c13 
I've also got this from the request, and this doesn't seem to be matching with the current RequestEnvelope proto

```
1: 1
2: 2 //What is this second field?
3: 1
4 {
  1 { //Repeated (not as the current protos)
    1: "google"
  }
}
```

So i editted the protos, like this:

```
message NewResponseEnvelope {
    int32 status_code = 1;
    int32 unk2 = 2;
    int32 unk3 = 3;
    repeated unk4msg unk4 = 4;

    message unk4msg {
        int32 auth_status = 1;
    }
}

message NewRequestEnvelope {
    int32 status_code = 1;
    int32 unk2 = 2;
    int32 unk3 = 3; //Guess it's not request ID...
    repeated unk4msg unk4 = 4;

    message unk4msg {
        repeated AuthInfo auth_info = 1;

        message AuthInfo {
            string provider = 1;
        }
    }
}
```

**Comment by vankxr** [comment]
Does anyone know how to bypass those envelopes? I am making a custom server and I would like not having those :/

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
