### ISSUE TITLE
[Question] Fort IDs

### ISSUE THREAD

**Issue by vankxr** [AeonLucid/POGOProtos#235]
I was playing around with some map object dumps, and I would want to ask if anyone knows what is the formar for a fort_id string

It seems to be a string with 32 characters (maybe a md5 of something? Cell id?), a dot, and a number

Does anyone have precise information? Also spawn point ids work the same way (i guess).

Thanks :D

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
