### ISSUE TITLE
[Question] How to request pokemon is deployed in Gym?

### ISSUE THREAD

**Issue by R0g3r10LL31t3** [AeonLucid/POGOProtos#237]
Hello,

Is possible request the attribute if pokemon is deployed in Gym?

**Comment by DrDelay** [comment]
If [deployed_fort_id](https://github.com/AeonLucid/POGOProtos/blob/a01a480e461b3e2ef29f9f4de6c7af318025a321/src/POGOProtos/Data/PokemonData.proto#L16) is set it is deployed, that how it is done in [NicklasWallgren/PokemonGoAPI-PHP](https://github.com/NicklasWallgren/PokemonGoAPI-PHP/blob/d90e26ed5e94da9c92ce35eb67f4197eaa161ada/src/Api/Pokemon/Support/PokemonDetailsTrait.php#L299).

**Comment by R0g3r10LL31t3** [comment]
Nice, thanks DrDelay

**Comment by AeonLucid** [comment]
Closing this issue.
