### ISSUE TITLE
Usage of the new API

### ISSUE THREAD

**Issue by Kermel** [AeonLucid/POGOProtos#242]
Was anyone successful in making an API call with the new API that leaked couple of days ago? 

Details here:
https://www.reddit.com/r/pokemongodev/comments/5a0obu/api_release_how_to_get_the_leaked_file_to_work/

I honestly admit that this is probably beyond my current time limits (as it aparently requires knowledge of unicorn emulator and also using of a real IPA (in order to make the call for the hashing function if I am correct . both of which I do not possess :-) )

**Comment by AeonLucid** [comment]
There is now.

https://github.com/pogodevorg/pgoapi
