### ISSUE TITLE
PokemonData.proto not entirely correct

### ISSUE THREAD

**Issue by pokeolaf** [AeonLucid/POGOProtos#25]
Testing against some data i got by mitming the game running on a virtual android ive found out that parsing the PokemonData results in some skiped bytes. This indicates strongly, that the current proto definition is not entierly correct. I'll investigate this further but since i havnt worked with protobuf before this will take some time (if i even manage to figure something out).

**Comment by AeonLucid** [comment]
Can you confirm that it's fixed by this PR?
https://github.com/AeonLucid/POGOProtos/pull/26

**Comment by esfomeado** [comment]
Tested with the latest revision and the move names aren't correct.
move_name_000 and Signal Beam

**Comment by rubenvereecken** [comment]
Update @esfomeado ?

**Comment by esfomeado** [comment]
@rubenvereecken I didn't had that much time for test this. I will let you know by the end of weekend.

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
