### ISSUE TITLE
Playerstats - Incorrect wire format

### ISSUE THREAD

**Issue by NicklasWallgren** [AeonLucid/POGOProtos#251]
Incorrect wire format for field 3, expected: 0 got: 2
Incorrect wire format for field 10, expected: 0 got: 2

**Comment by AeonLucid** [comment]
Can you try adding [packed=true] behind field 3 and 10, and then recompile?

Like done here https://github.com/AeonLucid/POGOProtos/blob/d20dcab6dded587399b1bfc54430bb7536f5adfa/src/POGOProtos/Data/Capture/CaptureAward.proto#L9.

I remember that this was a fix for errors like that sometimes.

**Comment by NicklasWallgren** [comment]
Thanks, closing this issue.
