### ISSUE TITLE
Update to version 2.5.x - APK 0.53.1 - IPA 1.23.1

### ISSUE THREAD

**Issue by rmkane** [AeonLucid/POGOProtos#263]
The APK has been updated to version 0.53.1

> http://www.apkmirror.com/apk/niantic-inc/pokemon-go/pokemon-go-0-53-1-release/pokemon-go-0-53-1-android-apk-download/

Recent Datamine

* https://thesilphroad.com/news/pokemon-go-v053-apk-mine-new-moves-and-evolution-items
* https://www.reddit.com/r/TheSilphRoad/comments/5okrcw/the_silph_roads_apk_mine_of_v0531_is_complete_38/

**Comment by apavlinovic** [comment]
Metadata dump and more data mining efforts:

* https://gist.github.com/apavlinovic/c326381e13909bd0ff3b3ec4a17642e7

* http://pokemongohub.net/0-53-1-data-mining-unown-added-new-avatar-customization-options/
