### ISSUE TITLE
Create GAME_MASTER.json

### ISSUE THREAD

**Issue by celandro** [AeonLucid/POGOProtos#265]
A JSON file generated from the GAME_MASTER code would be of great use to many and a perfect supplement to this project.

The code for it is already complete in JAVA: 
https://github.com/celandro/pokebattler-fight/blob/master/src/test/java/POGOProtos/GenerateJSON.java

It is extremely trivial, simply using the protobuf 3.X JSON generation capabilities. You should be able to implement the same in python if you like.  The addLegacyMoves is of course only necessary for my own site, up to you whether you would want that in your version.

Separately, if there is interest in me creating a java module for protos I could probably make one to fill that gap in the language support.

**Comment by apavlinovic** [comment]
I second this!

**Comment by Ashok-Varma** [comment]
@celandro please create a java module for protos. Since every other language has there own repos

**Comment by celandro** [comment]
Java repo: https://github.com/celandro/pogoprotos-java

We have also created a place for json hosting here:
https://github.com/BrunnerLivio/pokemongo-game-master

I would still rather merge this into this project though

**Comment by celandro** [comment]
Fixed with https://github.com/AeonLucid/POGOProtos/pull/276

**Comment by celandro** [comment]
This issue has been open for awhile. Can we get this merged? I know the gamemaster isnt technically a proto but its pretty closely related.

Also the java repo is pretty regularly updated
