### ISSUE TITLE
Extracting the .proto files

### ISSUE THREAD

**Issue by ScottPierce** [AeonLucid/POGOProtos#27]
Any chance you could explain how you go the .proto files for Pokemon Go? I've tried for hours to find a way to extract them myself and eventually gave up. I'd love to better understand how you were able to get ahold of them.

**Comment by bbotelho3** [comment]
You can find some information here: https://www.reddit.com/r/pokemongodev/comments/4svl1o/guide_to_pokemon_go_server_responses/
