### ISSUE TITLE
0.59.1 Support

### ISSUE THREAD

**Issue by Lord-Haji** [AeonLucid/POGOProtos#279]
0.59.1 is already out ! and I am 100 % sure about there are several proto changes

**Comment by BrunnerLivio** [comment]
PR #278 (V2.8.0 with v0.59.1 proto version) is already submitted.

**Comment by celandro** [comment]
What is blocking the merge?

**Comment by AeonLucid** [comment]
#278 is merged. 😄

**Comment by mhetralla** [comment]
I [compiled Snorlax](https://github.com/mhetralla/Snorlax/commits/0.59.1) with the last POGOProtos (2.8.0), but it didn't work. @simonward86 said in https://github.com/alucas/Snorlax/issues/54 that it didn't worked for him neither.
Have you tried the protos with any other aplication?
