### ISSUE TITLE
source for .proto files

### ISSUE THREAD

**Issue by zhirzh** [AeonLucid/POGOProtos#29]
This is just a question, not an issue - didn't know where else to ask.

How did you get all these `.proto` files? Was it all intelligent guess work or there is some better, more formal method?

**Comment by bbotelho3** [comment]
Reverse engineered from the calls and the apk, along with guess work. You can see more information here: https://www.reddit.com/r/pokemongodev/comments/4svl1o/guide_to_pokemon_go_server_responses/
