### ISSUE TITLE
POGOProtos.Data.PlayerData.tutorialState invalid

### ISSUE THREAD

**Issue by andrewmunro** [AeonLucid/POGOProtos#35]
Using the latest Protobufs, I get `ERROR: Illegal wire type for field Message.Field .POGOProtos.Data.PlayerData.tutorialState: 2 (0 expected)` when trying to convert them using protobufjs.

This occurs when doing a `RequestType.GET_PLAYER` request and I decode the response using the `Networking.Responses.GetPlayerResponse` protobuf. 

I guess the TutorialState enum is incorrect. I can convert the response correctly if I set https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Data/PlayerData.proto#L15 to `bytes`

**Comment by AeonLucid** [comment]
Can you try to set it to
`.POGOProtos.Enums.TutorialState tutorial_state = 7;`
and see if it works correctly?

**Comment by andrewmunro** [comment]
Nope same error :(

**Comment by AeonLucid** [comment]
Woops uhm, how about:
`repeated .POGOProtos.Enums.TutorialState tutorial_state = 7 [packed=true];`

This _should_ work.

**Comment by andrewmunro** [comment]
Works! 

```
  username: 'dave976',
  team: 1,
  tutorialState: [ 0, 1, 3, 4, 7 ],
  ...
```

Now I'm having issues with https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Data/PokemonData.proto#L34 ... it works when I set it to float.

**Comment by AeonLucid** [comment]
Fixed the tutorial state. (https://github.com/AeonLucid/POGOProtos/commit/966250b36e2640b841e25b8a231ff0468f0c4b4d)

I think that the multiplier should be a float indeed.

**Comment by rastapasta** [comment]
protobuf.js doesn't handle syntax3 repeated fields in a correct way yet
https://github.com/dcodeIO/protobuf.js/issues/432

**Comment by rubenvereecken** [comment]
Any objections to closing the issue?

**Comment by andrewmunro** [comment]
Thanks :)
