### ISSUE TITLE
Rename Reserved keyword "class"?

### ISSUE THREAD

**Issue by netizen01** [AeonLucid/POGOProtos#39]
Settings.Master.PokemonSettings uses "class" as one of the properties:

`.POGOProtos.Enums.PokemonClass class = 14;`

"class" is a reserved word in various languages and when running protoc for those languages, it can result in some invalid code.

Ideally the fix for this issue is in the code generators, but while we wait for those parsers to get better, a quick solution here is rename "class" to "clazz".

`.POGOProtos.Enums.PokemonClass clazz = 14;`

**Comment by AeonLucid** [comment]
Thank you!

I've fixed it. (https://github.com/AeonLucid/POGOProtos/commit/1d8e351c2b3ba3c5692156a12973c5da7faac444)
