### ISSUE TITLE
Conquered gyms is always 0

### ISSUE THREAD

**Issue by esfomeado** [AeonLucid/POGOProtos#43]
It shows always that you have 0 gyms.

**Comment by kaneoriley** [comment]
Can confirm this is happening to me. Using https://github.com/justinleewells/pogo-optimizer, when I switch to the proxied connection the game permanently thinks I have 0 pokemon in gyms, as soon as I remove the proxy it goes back to the correct number.

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
