### ISSUE TITLE
Set lure module on Pokestop?

### ISSUE THREAD

**Issue by D1no** [AeonLucid/POGOProtos#45]
I just stumbled over the repo over reddit and did not think, the protos reengineering is already that far. Incredible.

As far as I can tell, is it possible to **programmatically set lure modules on pokestops**? I.e. I want to set two lure modules and have two players walk back and forth.

Currently using the node wrapper.

**Comment by rubenvereecken** [comment]
Yes

**Comment by rastapasta** [comment]
[<-] Request for AddFortModifier  { modifier_type: 'ITEM_TROY_DISK',
  fort_id: 'foobar',
  player_latitude: lat
  player_longitude: lng } 

[->] Response for AddFortModifier  {} 

[<-] Request for FortDetails  { fort_id: 'foobar',
  latitude: lat,
  longitude: lng } 

[->] Response for FortDetails  { fort_id: 'foobar',
  name: 'name,
  image_urls: [ 'img' ],
  type: 'CHECKPOINT',
  latitude: lat,
  longitude: lng,
  modifiers: 
   [ { item_id: 'ITEM_TROY_DISK',
       expiration_timestamp_ms: '1469291229349',
       deployer_player_codename: 'yourUserName' } ] }

**Comment by D1no** [comment]
Ah, so the lure module is called `ITEM_TROY_DISK`? I thought that was the players lure smoke item... Thx for the example @rastapasta. PS: Der Node-Wrapper ist echt Klasse!

**Comment by rastapasta** [comment]
It's actually both - player's inventory item and fort modifier - both are referencing the same ENUM (POGOProtos.Inventory.Item.ItemId) 😊

**Comment by D1no** [comment]
Aaah now I see 😅  thx! Lets hope the fun lasts a while
