### ISSUE TITLE
get_map_objects not returning forts/pokemon

### ISSUE THREAD

**Issue by abhirathod95** [AeonLucid/POGOProtos#59]
Using the latest version of the Protos, I can't seem to get the forts and pokemon listed in the response dictionary when I call get_map_objects. The version used in the pgoapi (https://github.com/tejado/pgoapi) seems to work perfectly fine, but when the same request is made using the latest code, it doesn't seem to list any forts or pokemon. It still lists cell ids and session timestamps and the status returned is 1.

**Comment by erhan-** [comment]
Don't do f2i(). Let the lat and lng values be float.

**Comment by abhirathod95** [comment]
That made it work! Thanks! :)
