### ISSUE TITLE
Compiled version for Node

### ISSUE THREAD

**Issue by rubenvereecken** [AeonLucid/POGOProtos#6]
Hi, @rastapasta wrote a script that compiles your protos to a `desc file`. I quickly created a requirable node package for easy use across projects, no need to have to recompile the protos myself all the time if the libraries I depend on have them anyway. Here it is: https://github.com/rubenvereecken/node-pokemongo-protobuf

It's different from the code generation approach in that requiring this module gives you an object you can work with and has everything contained.

Think we could link this here?

**Comment by AeonLucid** [comment]
It's linked in the readme now.
