### ISSUE TITLE
Egg target km always 0

### ISSUE THREAD

**Issue by Wroud** [AeonLucid/POGOProtos#64]
Server response contains eggs have egg_km_walked_target and egg_km_walked_start is 0
Is this protobuff problem?

**Comment by Wroud** [comment]
Sorry, my wrong, i need itemsTemplates

**Comment by Wroud** [comment]
problem with variable type, egg_km_walked_target and egg_km_walked_start must be double, now its int32 fix plz

**Comment by vmarchaud** [comment]
[???](https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Data/PokemonData.proto#L20-L#21)

**Comment by Wroud** [comment]
oh sorry, have old version

**Comment by vmarchaud** [comment]
But the problem is the same with double, the servers arent sending the egg_walked_start value so its always 0.
