### ISSUE TITLE
Question: Function to retrieve other user's details?

### ISSUE THREAD

**Issue by jankcat** [AeonLucid/POGOProtos#65]
Hello,

I am looking to see if there is a function to retrieve another user's basic details, like level, pokemon caught, etc. 
The best I could see was the GetPlayerProfile call, but it seems to retrieve my own details even if I provide the player_name in the message... any ideas or tips?

Note: wouldnt let me label this as question, I guess I dont have permissions. :P

**Comment by rastapasta** [comment]
Sadly wise there isn't a possibility to request this kind of data from the API AFAIK. The API seems to completely ignore passed player_name.

**Comment by jankcat** [comment]
Bah. That's too bad. Maybe in a future update containing social features...

**Comment by jankcat** [comment]
Thanks for the comment though!
