### ISSUE TITLE
Software License

### ISSUE THREAD

**Issue by zeevallin** [AeonLucid/POGOProtos#67]
I would love if this codebase had some kind of software license. I would suggest MIT since that protects you from liability and lets anyone use this for any project. Closed or open source. Thoughts?

**Comment by rubenvereecken** [comment]
I'd agree, this has nothing to benefit from gpl for example. Have to compare with another one tomorrow then suggest to the other contributors.

**Comment by olegshulyakov** [comment]
You can use Apache licence. It is comfortable to use in project with open and close source

**Comment by AeonLucid** [comment]
License has been added. https://github.com/AeonLucid/POGOProtos/commit/e28f92437bc1c94a0cddf83e2255c4bd518e9853
