### ISSUE TITLE
Incense Encounters Don't Work

### ISSUE THREAD

**Issue by Nostrademous** [AeonLucid/POGOProtos#69]
Using latest commits for protos

I can do: UseIncense -> GetIncensePokemon() -> IncenseEncounter() and here it complaints and throws "INCENSE_ENCOUNTER_NOT_AVAILABLE"

GetIncensePokemon() returns "INCENSE ENCOUNTER AVAILABLE". I then invoke IncenseEncounter with the fixed64 encounter_id and string encounter_location, but get the INCENSE_ENCOUNTER_NOT_AVAILABLE return.

I did modify my proto for IncenseEncounterMessage to be fixed64 for encounter_id to match the GetIncensePokemon response.

Still doesn't work unfortunately.

**Comment by prorook** [comment]
encounter_id for the encounter message needs to be int64...even though the encounter_id on the incensePokemon message is fixed64. I had the same issue, but I got it working by reverting the encounter message back to int64.

**Comment by Nostrademous** [comment]
@prorook thanks, I will give it a try. What's the correct way to transform a fixed64 to an int64 in python? I ask cause I get errors thrown if I don't do a conversion (perhaps because I use an older version of protobuf).

**Comment by Nostrademous** [comment]
Thank you, got it working after fixing the GetIncensePokemonResponse to PokemonId enum, rather than int32

**Comment by Nostrademous** [comment]
Actually, it still fails at times...

for large encounter_id type-casting to python's int() doesn't work at times.

I just got two encounter_ids (1 worked, 1 didn't)
WORKED: 6180230722423979422
    FAILED: 10965396974330624794 <-- this is bigger than int64 and smaller than uint64

**Comment by RyanHope** [comment]
How are incense encounters caught without a spawn_point_id?

**Comment by Nostrademous** [comment]
@RyanHope they are not, you get one from GetIncencePokemon response.

**Comment by RyanHope** [comment]
Not according to https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Networking/Responses/GetIncensePokemonResponse.proto

**Comment by Nostrademous** [comment]
@RyanHope it's called "encounter_location"

**Comment by rubenvereecken** [comment]
This is about to be fixed with `LureInfo` being replaced. Spawn point ids are actually fort ids in this case.
