### ISSUE TITLE
ResponseEnvelope.status_code occasionally length-delimited

### ISSUE THREAD

**Issue by tvald** [AeonLucid/POGOProtos#70]
`ResponseEnvelope.status_code` very occasionally seems to be length-delimited, as in these two log excerpts:

> [+++] Request to pgorelease.nianticlabs.com//plfe/287/rpc
> [+] Request for action GetMapObjects:
> [+] Request for action GetHatchedEggs:
> [+] Request for action GetInventory:
> [+] Request for action CheckAwardedBadges:
> [+] Request for action DownloadSettings:
> [+] Waiting for response...
> [+] Response for action GetMapObjects
> [+] Response for action GetHatchedEggs
> [+] Response for action GetInventory
> [+] Response for action CheckAwardedBadges
> [+] Response for action DownloadSettings
> [-] Parsing protobuf of ResponseEnvelope failed: Error: Illegal wire type for field Message.Field .POGOProtos.Networking.Envelopes.ResponseEnvelope.status_code: 2 (0 expected)
> 
> [+++] Request to pgorelease.nianticlabs.com//plfe/287/rpc
> [+] Request for action GetAssetDigest:
> [+] Request for action GetHatchedEggs:
> [+] Request for action GetInventory:
> [+] Request for action CheckAwardedBadges:
> [+] Request for action DownloadSettings:
> [+] Waiting for response...
> [+] Response for action GetAssetDigest
> [+] Response for action GetHatchedEggs
> [+] Response for action GetInventory
> [+] Response for action CheckAwardedBadges
> [+] Response for action DownloadSettings
> [-] Parsing protobuf of ResponseEnvelope failed: Error: Illegal wire type for field Message.Field .POGOProtos.Networking.Envelopes.ResponseEnvelope.status_code: 2 (0 expected)

**Comment by rubenvereecken** [comment]
Huh I don't see how it could be length delimited _sometimes_. Mind trying it out with string type and see if that works out better for you?

**Comment by NicklasWallgren** [comment]
This may be related. 'Incorrect wire format for field 1, expected: 0 got: 2'.

**Comment by NicklasWallgren** [comment]
@tvald The server probably returned a response status code of 500 which you didn't handle correctly. I had the same problem

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
