### ISSUE TITLE
EggIncubator pokemon_id

### ISSUE THREAD

**Issue by ghost** [AeonLucid/POGOProtos#74]
The pokemon_id field in the EggIncubator message seems to be uint64 instead of fixed64. After the last commit the returned pokemonId of an incubator is always 0 and the next fields are also wrong.
Example code that works with uint64 

``` csharp
public async Task<IEnumerable<PokemonData>> GetPokemons()
{
    var inventory = await session.GetInventory();
    return
        inventory.InventoryDelta.InventoryItems.Select(i => i.InventoryItemData?.PokemonData)
            .Where(p => p != null);
}
private async Task<EggIncubators> GetPlayerIncubators()
{
    var inventory = await session.GetInventory();

    return
        inventory.InventoryDelta.InventoryItems.Select(i => i.InventoryItemData.EggIncubators)
            .Where(p => p != null).First();
}
private async Task IncubateEggs()
{
    var playerPokemons = await GetPlayerPokemonsData();
    var playerIncubators = await GetPlayerIncubators();

    var eggs = playerPokemons
        .Where(p => p.IsEgg)
        .Where(p => p.EggIncubatorId == string.Empty)
        .OrderByDescending(p => p.EggKmWalkedTarget).ToList();

    if (eggs.Count() == 0)
        return;

    var incubators = playerIncubators.EggIncubator
        .Where(p => p.IncubatorType != EggIncubatorType.IncubatorUnset)
        .Where(p => p.UsesRemaining > 0 || p.ItemId == ItemId.ItemIncubatorBasicUnlimited)
        .Where(p => p.PokemonId == 0)
        .OrderByDescending(p => p.UsesRemaining).ToList();

    if (incubators.Count() == 0)
        return;

    foreach (var incubator in incubators)
    {
        if (eggs.Count() == 0)
            break;

        var firstEgg = eggs.First();
        eggs.Remove(firstEgg);

        var useIncubatorResponse = await session.UseItemEggIncubator(incubator.Id, firstEgg.Id);

        Log.Info($"incubator used [ {useIncubatorResponse?.Result} ]");

        await Task.Delay(250);
    }
}
```

**Comment by rubenvereecken** [comment]
Alright, rolling back, we'll have to figure out which ones to keep carefully though. Thanks!

**Comment by jabbink** [comment]
Hmm, fields after it are okay for me, currently checking the use of an incubator by comparing the distance walked

**Comment by rubenvereecken** [comment]
Rolled back my mass change except for one that got reported. Added a note for this one. Curious to hear more!

**Comment by Grover-c13** [comment]
do you have any trouble with other protos with the pokemon id?

**Comment by N3messys** [comment]
@jabbink What language are you using the protos with ?
I've encountered this in C#

**Comment by ghost** [comment]
I've closed it by mistake. 
@jabbink What language are you using the protos with ? I'm testing with C# right now.

**Comment by jabbink** [comment]
I use Java @N3messys

**Comment by rubenvereecken** [comment]
By the way we have Slack: 

https://pkre.slack.com/messages/pogoprotos/

Invite at https://shielded-earth-81203.herokuapp.com/

**Comment by ghost** [comment]
I've joined Slack.

These are the objects I have in C# 

> uint64
> {{ "id": "EggIncubatorProto-3573192326632007880", "itemId": "ITEM_INCUBATOR_BASIC_UNLIMITED", "incubatorType": "INCUBATOR_DISTANCE", "pokemonId": "7057783031845893019", "startKmWalked": 42.868797302246094, "targetKmWalked": 47.868797302246094 }}
> 
> fixed64
> {{ "id": "EggIncubatorProto-3573192326632007880", "itemId": "ITEM_INCUBATOR_BASIC_UNLIMITED", "incubatorType": "INCUBATOR_DISTANCE", "startKmWalked": 42.868797302246094, "targetKmWalked": 47.868797302246094 }}

Same Id, ItemId, but on fixed64 the pokemonId is wrong (0).

Edit : the startKmWalked and targetKmWalked fields are correct. My bad.

**Comment by vmarchaud** [comment]
Both are parsed into ulong in C# following the [offical doc](https://developers.google.com/protocol-buffers/docs/proto3#scalar), it shouldnt be a problem no ?

**Comment by ghost** [comment]
Perhaps I interpreted the packet wrong and until the egg has hatched the pokemonId indeed has to be 0 ?

**Comment by vmarchaud** [comment]
Yes, the pokemonID is sent with the GetHatchedEggsMessage :)

**Comment by ghost** [comment]
The fixed64 seems to be correct then. I will mark this as closed.
The revert should be reverted.
