### ISSUE TITLE
UpgradePokemonMessage

### ISSUE THREAD

**Issue by iCyclus** [AeonLucid/POGOProtos#80]
UpgradePokemonMessage.proto has a uint64 for the pokemon_id and i think it's wrong...
I tried multiple times to get this to work but i can't,
so im guessing it has to be fixed64?!

**Comment by rubenvereecken** [comment]
Me thinks you're right https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Networking/Requests/Messages/UpgradePokemonMessage.proto#L5
