### ISSUE TITLE
Import was not found or had errors.

### ISSUE THREAD

**Issue by jaspervdm** [AeonLucid/POGOProtos#82]
I tried to compile the latest master (`cbf0b08`), it gave me a bunch of errors:
- `POGOProtos/Inventory/PokemonFamily.proto: File not found.`
- `POGOProtos/Inventory/InventoryItemData.proto: Import "POGOProtos/Inventory/PokemonFamily.proto" was not found or had errors.`
- `POGOProtos/Inventory/InventoryItemData.proto:25:9: ".POGOProtos.Inventory.Candy" is not defined.`
- `POGOProtos/Inventory/InventoryItem.proto: Import "POGOProtos/Inventory/InventoryItemData.proto" was not found or had errors.`
- `POGOProtos/Inventory/InventoryItem.proto:9:9: ".POGOProtos.Inventory.InventoryItemData" is not defined.`
- `POGOProtos/Inventory/InventoryDelta.proto: Import "POGOProtos/Inventory/InventoryItem.proto" was not found or had errors.`
- `POGOProtos/Inventory/InventoryDelta.proto:9:18: ".POGOProtos.Inventory.InventoryItem" is not defined.`
- `POGOProtos/Networking/Responses/GetInventoryResponse.proto: Import "POGOProtos/Inventory/InventoryDelta.proto" was not found or had errors.`
- `POGOProtos/Networking/Responses/GetInventoryResponse.proto:8:9:".POGOProtos.Inventory.InventoryDelta" is not defined.`
- `POGOProtos/Settings/Master/PokemonSettings.proto: Import "POGOProtos/Enums/PokemonId.proto" was listed twice.`
- `POGOProtos/Networking/Responses/DownloadItemTemplatesResponse.proto: Import "POGOProtos/Settings/Master/PokemonSettings.proto" was not found or had errors.`
- `POGOProtos/Networking/Responses/DownloadItemTemplatesResponse.proto:29:17: ".POGOProtos.Settings.Master.PokemonSettings" is not defined.`
- `POGOProtos/Networking/Responses/GetIncensePokemonResponse.proto:6:9: ".POGOProtos.Enums.PokemonId" is not defined.`
- `POGOProtos/Inventory/PokemonFamily.proto: File not found.`
- `POGOProtos/Inventory/InventoryItemData.proto: Import "POGOProtos/Inventory/PokemonFamily.proto" was not found or had errors.`
- `POGOProtos/Inventory/InventoryItemData.proto:25:9: ".POGOProtos.Inventory.Candy" is not defined.`
- `POGOProtos/Inventory/InventoryItem.proto: Import "POGOProtos/Inventory/InventoryItemData.proto" was not found or had errors.`
- `POGOProtos/Inventory/InventoryItem.proto:9:9: ".POGOProtos.Inventory.InventoryItemData" is not defined.`
- `POGOProtos/Inventory/InventoryDelta.proto: Import "POGOProtos/Inventory/InventoryItem.proto" was not found or had errors.`
- `POGOProtos/Inventory/InventoryDelta.proto:9:18: ".POGOProtos.Inventory.InventoryItem" is not defined.`

I think there are more but I just copied some of them. Am I doing something wrong or should these proto's be fixed?

**Comment by AeonLucid** [comment]
@rubenvereecken

**Comment by rubenvereecken** [comment]
:eggplant:
