### ISSUE TITLE
GetMapObjectsMessage > MapCell has only s2_cell_id and current_timestamp_ms

### ISSUE THREAD

**Issue by pimpcapital** [AeonLucid/POGOProtos#83]
I am using a python compiled version of v1.0.

MapCells in GetMapObjectsMessage has only 2 fields as stated in the title.
Some important fields such as forts, spawn_points etc are missing

**Comment by golddevelopment** [comment]
I'm having the same issue
![screen shot 2016-07-27 at 16 55 28](https://cloud.githubusercontent.com/assets/11904160/17179874/01326b0a-541b-11e6-839e-056d93339dcb.png)

**Comment by jabbink** [comment]
How many cells are you requesting? > 100? There's your problem.

< 100? What is the furthest distance of a cell you are requesting. > 1.5 km? That's your problem.

<1.5 km? Did you set your location in the envelope? No? That's your problem, you're "infinitely" away from the requested cells and you answered the distance question incorrect.

**Comment by jabbink** [comment]
Forgot one: which zoom level are you requesting? Only level 15 will return pokestops, gyms **and** pokemon spawns.

Only level (I think) 12 to 15 return Pokemon spawns (but < 15 no more gyms/stops)

**Comment by erhan-** [comment]
Don't use f2i. Use double.

**Comment by golddevelopment** [comment]
@erhan- Thanks, that was the problem ¬¬

**Comment by rubenvereecken** [comment]
Hey @jabbink that was a really good explanation on the cells right there. This is the kind of stuff that make protobufs really valuable; they're a repository of known constraints. I would _love_ to merge in a PR describing that in the comments of the fields in question.

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
