### ISSUE TITLE
Nickname_Pokemon returns either status 2(invalid name) or 3(pokemon not found)

### ISSUE THREAD

**Issue by pimpcapital** [AeonLucid/POGOProtos#84]
using python compiled version v1.0

2 fields:

e.g.
pokemon_id = (the super long pokemon integer id from pokemon['id'])
nickname = "test123"
response {status: 3}

pokemon_id = (the super long pokemon integer id from pokemon['id'])
nickname = "12.34-56A-78B-90D" # too long
response {status: 2}

I was planning to use the nickname feature to tag my pokemons with their IV values. All chars are ASCII, so there shouldn't be any encoding issue.

**Comment by pimpcapital** [comment]
maybe need a fix similar to #75

**Comment by pimpcapital** [comment]
confirmed. uint64 is the right type.

**Comment by pimpcapital** [comment]
created #85 for this fix

**Comment by AeonLucid** [comment]
Closing this issue, let me know if this is still relevant.
