### ISSUE TITLE
Unknown fields in Envelopes

### ISSUE THREAD

**Issue by Lennix** [AeonLucid/POGOProtos#90]
Just wanted to start a discussion on the unknown fields in the request and response envelope to gather some intel.

Someone mentioned that Unknown12 might the the time in ms since last GPS refresh. Do we have any way to confirm that?

Unknown6.Unknown1 mostly seems to be 6. I saw it with 5 once when Requests[] was empty.

Discussion on reddit: https://www.reddit.com/r/pokemongodev/comments/4tzgbw/anyone_knowing_more_about_the_infamous_unknown/

**Comment by Lennix** [comment]
Linking Issue #94 (why duplicate) about Unknown 12

**Comment by Lennix** [comment]
PR #11 also talks about Unknown fields

**Comment by Lennix** [comment]
Unknown 6 is only in the response header if we sent Unknown6 with the request

**Comment by tjhorner** [comment]
PR I just opened (#98) solves part of Unknown6.

**Comment by Lennix** [comment]
I did some investigation on unknown6.unknown2.unknown1 or Unknown ByteString or UnknownBS:
- Its always 32 bytes (some kind of header) + n \* 256 bytes with n >= 1 (payload)
- If the RequestID is the same, UnknownBS is the same (makes sense)
- Sometimes the header is the same on consecutive requests and the payload only differs in a couple byte (which could mean we are not facing hashed values?)
- Payload does not correlate with GPS coordinates
- n does not correlate with unknown12
- n correlates with time passed since last packet (one block per roughly 500-700ms)
- Header does not correlate with request_type nor request_id
- The header also repeats on non-consecutive packets (with completely different payload)

**Comment by tjhorner** [comment]
I strongly believe that it's some type of logging then. Niantic did this with Ingress, and the fact that it has a header, padding (the n \* 256 bytes you mentioned) and then the payload suggests some type of encryption... which they did with Ingress. They may be logging player events such as screen tapping.

**Comment by Lennix** [comment]
To be clear, the structure is
- 32 bytes header
- 256 bytes payload (n times)

The length of the payload (n) is depending on time past since last packet sent.
Also, on some consecutive requests, only a couple byte are changed within the payload.

**Comment by Lennix** [comment]
I'll close this since its fixed.
