### ISSUE TITLE
There is still problem with proto compilation for java at least (inventory related)

### ISSUE THREAD

**Issue by Nader-Sl** [AeonLucid/POGOProtos#93]
`Compiling \POGOProtos\Networking\Responses\GetInventoryResponse.proto..
POGOProtos/Inventory/PokemonFamily.proto: File not found.
POGOProtos/Inventory/InventoryItemData.proto: Import "POGOProtos/Inventory/PokemonFamily.proto" was not found or had errors.
POGOProtos/Inventory/InventoryItemData.proto:25:9: ".POGOProtos.Inventory.Candy" is not defined.
POGOProtos/Inventory/InventoryItem.proto: Import "POGOProtos/Inventory/InventoryItemData.proto" was not found or had errors.
POGOProtos/Inventory/InventoryItem.proto:9:9: ".POGOProtos.Inventory.InventoryItemData" is not defined.
POGOProtos/Inventory/InventoryDelta.proto: Import "POGOProtos/Inventory/InventoryItem.proto" was not found or had errors.
POGOProtos/Inventory/InventoryDelta.proto:9:18: ".POGOProtos.Inventory.InventoryItem" is not defined.
POGOProtos/Networking/Responses/GetInventoryResponse.proto: Import "POGOProtos/Inventory/InventoryDelta.proto" was not f`

**Comment by rubenvereecken** [comment]
Try again please.

**Comment by Nader-Sl** [comment]
Thank you! works now :)
